PhotoBucket:
  Type: AWS::S3::Bucket
  Properties:
    BucketName: ${self:custom.PhotoBucket.name}

PhotoBucketPolicy:
  Type: AWS::S3::BucketPolicy
  Properties:
    Bucket: !Ref PhotoBucket
    PolicyDocument:
      Statement:
        - Sid: PublicRead
          Effect: Allow
          Principal: '*'
          Action:
            - s3:GetObject
            - s3:ListBucket
          Resource: 
            - arn:aws:s3:::${self:custom.PhotoBucket.name}
            - arn:aws:s3:::${self:custom.PhotoBucket.name}/*